apiVersion: v1
kind: Namespace
metadata:
  name: ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqdeployment
  namespace: ms
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_ERLANG_COOKIE
              value: "SWQOKODSQALRPCLNMEQG"
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqservice
  namespace: ms
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: 15672-tcp
      port: 15672
      targetPort: 15672
    - name: 5672-tcp
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msappdeployment
  namespace: ms
  labels:
    app: ms_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms_app
  template:
    metadata:
      labels:
        app: ms_app
    spec:
      containers:
        - name: app
          env:
            - name: PORT
              value: "3000"
            - name: RABBIT_MQ_QUEUE_SERVICE
              value: "queue_service"
            - name: RABBIT_MQ_EVENT_SERVICE
              value: "event_service"
            - name: RABBIT_MQ_PROTOCOL
              value: "amqp"
            - name: RABBIT_MQ_HOSTNAME
              value: "rabbitmqservice.ms"
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USERNAME
              value: "rabbitmq"
            - name: RABBIT_MQ_PASSWORD
              value: "rabbitmq"
          image: guilhermedmcassis/ms_app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: msappservice
  namespace: ms
spec:
  selector:
    app: msappservice
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mseventconsumerdeployment
  namespace: ms
  labels:
    app: ms_event_consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms_event_consumer
  template:
    metadata:
      labels:
        app: ms_event_consumer
    spec:
      containers:
        - name: ms-event-consumer
          env:
            - name: RABBIT_MQ_QUEUE_SERVICE
              value: "queue_service"
            - name: RABBIT_MQ_EVENT_SERVICE
              value: "event_service"
            - name: RABBIT_MQ_PROTOCOL
              value: "amqp"
            - name: RABBIT_MQ_HOSTNAME
              value: "rabbitmqservice.ms"
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USERNAME
              value: "rabbitmq"
            - name: RABBIT_MQ_PASSWORD
              value: "rabbitmq"
          image: guilhermedmcassis/ms_event_consumer:latest
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msreceiverdeployment
  namespace: ms
  labels:
    app: ms_receiver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms_receiver
  template:
    metadata:
      labels:
        app: ms_receiver
    spec:
      containers:
        - name: ms-receiver
          env:
            - name: RABBIT_MQ_QUEUE_SERVICE
              value: "queue_service"
            - name: RABBIT_MQ_EVENT_SERVICE
              value: "event_service"
            - name: RABBIT_MQ_PROTOCOL
              value: "amqp"
            - name: RABBIT_MQ_HOSTNAME
              value: "rabbitmqservice.ms"
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_USERNAME
              value: "rabbitmq"
            - name: RABBIT_MQ_PASSWORD
              value: "rabbitmq"
          image: guilhermedmcassis/ms_receiver:latest
          imagePullPolicy: Always
