version: "3.3"

services:
  app:
    networks:
      - my-network
    build: ../api-service/
    ports:
      - "3000:3000"
  ms-event-consumer:
    networks:
      - my-network
    build: ../ms-event-consumer/
  ms-receiver:
    networks:
      - my-network
    build: ../ms-receiver/
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '15672'
      - '5672'
    networks:
      - my-network

networks:
  my-network:
    external: true
