apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ms
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    spec:
      metadata:
        labels:
          app: rabbitmq
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              value: rabbitmq
            - name: RABBITMQ_ERLANG_COOKIE
              value: SWQOKODSQALRPCLNMEQG
          image: rabbitmq:management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
