apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ms
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
    - name: 15672-tcp
      port: 15672
      targetPort: 15672
    - name: 5672-tcp
      port: 5672
      targetPort: 5672
